[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino
lib_deps =
    fastled/FastLED
    https://github.com/m5stack/M5Unit-Joystick2.git
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
